### ISSUE TITLE
Uncaught Error: [$injector:unpr] Unknown provider: $$qProvider <- $$q <- $animate <- $compile

### ISSUE THREAD

**Issue by FedeG** [lelylan/devices-dashboard-ng#80]
In  **14937d9c.vendor.js:3**
Error in Angular: [Detail](https://docs.angularjs.org/error/$injector/unpr?p0=$$qProvider%20%3C-%20$$q%20%3C-%20$animate%20%3C-%20$compile)

Before error: 
```bash
git clone git@github.com:lelylan/devices-dashboard-ng.git
cd devices-dashboard-ng
npm install
bower install --allow-root --force-latest
grunt build
# open dist/index.html
```

Versions:
```bash
root@738f7c1472a7:/usr/src/app# npm --version
2.15.1
root@738f7c1472a7:/usr/src/app# bower --version
1.8.0
root@738f7c1472a7:/usr/src/app# grunt --version
grunt-cli v1.2.0
grunt v0.4.5
root@738f7c1472a7:/usr/src/app# node --version
v0.10.48
```

**Comment by FedeG** [comment]
#### Error detail:
**$$qProvider** service not found and the **$$qProvider** service is developed in `angular >= 1.3.0`

![captura de pantalla de 2017-02-01 16-16-21](https://cloud.githubusercontent.com/assets/4097554/22523066/ccd736e4-e89c-11e6-80eb-cbf73f354d50.png)

![captura de pantalla de 2017-02-01 16-16-57](https://cloud.githubusercontent.com/assets/4097554/22523071/d0e7b132-e89c-11e6-9b23-7de6a4c78411.png)

#### Question
When you remove this:
```diff
"resolutions": {
-    "angular": "1.2.22",
  "jasmine": "v1.3.1"
}
```
And execute this commands:
```bash
rm -rf app/bower_components
bower install --allow-root
```

Then, bower print this message:
```bash
Unable to find a suitable version for angular, please choose one by typing one of the numbers below:
    1) angular#1.2.6 which resolved to 1.2.6 and is required by angular-mocks#1.2.6, angular-route#1.2.6, angular-scenario#1.2.6, devices
    2) angular#>=1.0.0 <1.3.0 which resolved to 1.2.6 and is required by angular-moment#0.6.2
    3) angular#1.2.16 which resolved to 1.2.16 and is required by angular-animate#1.2.16
    4) angular#1.2.22 which resolved to 1.2.22 and is required by type-directive-ng#0.2.6
    5) angular#1.2.32 which resolved to 1.2.32 and is required by angular-animate#1.2.32, angular-touch#1.2.32
    6) angular#~1.2.22 which resolved to 1.2.32 and is required by oauth-ng#0.2.8
    7) angular#1.3.12 which resolved to 1.3.12 and is required by lelylan-ng#0.2.4
    8) angular#~1.3.12 which resolved to 1.3.20 and is required by device-directive-ng#0.2.8, oauth-ng#0.3.10
    9) angular#1.3.20 which resolved to 1.3.20 and is required by angular-animate#1.3.20, angular-touch#1.3.20
    10) angular#>=1.0.4 which resolved to 1.3.20 and is required by ng-clip#0.2.6
    11) angular#>=1.0.8 which resolved to 1.3.20 and is required by ngstorage#0.3.11

Prefix the choice with ! to persist it to bower.json
```

@andreareginato, why use this resolution: `"angular": "1.2.22"`?

**Comment by andreareginato** [comment]
Hi @FedeG. Bad to day, but I don't remember why there is this specific resolution. There is no real reason about this, meaning we should use the one that resolves the issue.

**Comment by FedeG** [comment]
i'm testing with new resolutions:

```diff
   "resolutions": {
-    "angular": "1.2.22",
-    "jasmine": "v1.3.1"
+    "jasmine": "v1.3.1",
+    "angular": "1.3.12",
+    "oauth-ng": "~0.3.8",
+    "angular-animate": "~1.3.12",
+    "angular-touch": "~1.3.12",
+    "zeroclipboard": "~2.2.0"
   }
 }
```

In testing, i found this error:
```log
Uncaught Error: [$injector:modulerr] Failed to instantiate module app due to:
Error: [$injector:modulerr] Failed to instantiate module lelylan.dashboards.device due to:
TypeError: Cannot read property 'push' of undefined
    at http://localhost/scripts/app.js:70:37
    at Object.invoke (http://localhost/bower_components/angular/angular.js:4185:17)
    at runInvokeQueue (http://localhost/bower_components/angular/angular.js:4091:35)
    at http://localhost/bower_components/angular/angular.js:4100:11
    at forEach (http://localhost/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost/bower_components/angular/angular.js:4081:5)
    at http://localhost/bower_components/angular/angular.js:4098:40
    at forEach (http://localhost/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost/bower_components/angular/angular.js:4081:5)
    at createInjector (http://localhost/bower_components/angular/angular.js:4007:11)
http://errors.angularjs.org/1.3.12/$injector/modulerr?p0=lelylan.dashboards.device&p1=TypeError%3A%20Cannot%20read%20property%20'push'%20of%20undefined%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fscripts%2Fapp.js%3A70%3A37%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4185%3A17)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4091%3A35)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4100%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4098%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4007%3A11)
    at http://localhost/bower_components/angular/angular.js:63:12
    at http://localhost/bower_components/angular/angular.js:4120:15
    at forEach (http://localhost/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost/bower_components/angular/angular.js:4081:5)
    at http://localhost/bower_components/angular/angular.js:4098:40
    at forEach (http://localhost/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost/bower_components/angular/angular.js:4081:5)
    at createInjector (http://localhost/bower_components/angular/angular.js:4007:11)
    at doBootstrap (http://localhost/bower_components/angular/angular.js:1445:20)
    at bootstrap (http://localhost/bower_components/angular/angular.js:1466:12)
http://errors.angularjs.org/1.3.12/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20lelylan.dashboards.device%20due%20to%3A%0ATypeError%3A%20Cannot%20read%20property%20'push'%20of%20undefined%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fscripts%2Fapp.js%3A70%3A37%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4185%3A17)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4091%3A35)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4100%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4098%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4007%3A11)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.12%2F%24injector%2Fmodulerr%3Fp0%3Dlelylan.dashboards.device%26p1%3DTypeError%253A%2520Cannot%2520read%2520property%2520'push'%2520of%2520undefined%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%252Fscripts%252Fapp.js%253A70%253A37%250A%2520%2520%2520%2520at%2520Object.invoke%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4185%253A17)%250A%2520%2520%2520%2520at%2520runInvokeQueue%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4091%253A35)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4100%253A11%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A323%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4081%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4098%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A323%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4081%253A5)%250A%2520%2520%2520%2520at%2520createInjector%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4007%253A11)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A63%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4120%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4098%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4007%3A11)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A1445%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A1466%3A12)
    at http://localhost/scripts/app.js:70:37
    at Object.invoke (http://localhost/bower_components/angular/angular.js:4185:17)
    at runInvokeQueue (http://localhost/bower_components/angular/angular.js:4091:35)
    at http://localhost/bower_components/angular/angular.js:4100:11
    at forEach (http://localhost/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost/bower_components/angular/angular.js:4081:5)
    at http://localhost/bower_components/angular/angular.js:4098:40
    at forEach (http://localhost/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost/bower_components/angular/angular.js:4081:5)
    at createInjector (http://localhost/bower_components/angular/angular.js:4007:11)
http://errors.angularjs.org/1.3.12/$injector/modulerr?p0=lelylan.dashboards.device&p1=TypeError%3A%20Cannot%20read%20property%20'push'%20of%20undefined%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fscripts%2Fapp.js%3A70%3A37%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4185%3A17)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4091%3A35)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4100%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4098%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4007%3A11)
    at http://localhost/bower_components/angular/angular.js:63:12
    at http://localhost/bower_components/angular/angular.js:4120:15
    at forEach (http://localhost/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost/bower_components/angular/angular.js:4081:5)
    at http://localhost/bower_components/angular/angular.js:4098:40
    at forEach (http://localhost/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost/bower_components/angular/angular.js:4081:5)
    at createInjector (http://localhost/bower_components/angular/angular.js:4007:11)
    at doBootstrap (http://localhost/bower_components/angular/angular.js:1445:20)
    at bootstrap (http://localhost/bower_components/angular/angular.js:1466:12)
http://errors.angularjs.org/1.3.12/$injector/modulerr?p0=app&p1=Error%3A%20%5B%24injector%3Amodulerr%5D%20Failed%20to%20instantiate%20module%20lelylan.dashboards.device%20due%20to%3A%0ATypeError%3A%20Cannot%20read%20property%20'push'%20of%20undefined%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fscripts%2Fapp.js%3A70%3A37%0A%20%20%20%20at%20Object.invoke%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4185%3A17)%0A%20%20%20%20at%20runInvokeQueue%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4091%3A35)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4100%3A11%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4098%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4007%3A11)%0Ahttp%3A%2F%2Ferrors.angularjs.org%2F1.3.12%2F%24injector%2Fmodulerr%3Fp0%3Dlelylan.dashboards.device%26p1%3DTypeError%253A%2520Cannot%2520read%2520property%2520'push'%2520of%2520undefined%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%252Fscripts%252Fapp.js%253A70%253A37%250A%2520%2520%2520%2520at%2520Object.invoke%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4185%253A17)%250A%2520%2520%2520%2520at%2520runInvokeQueue%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4091%253A35)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4100%253A11%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A323%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4081%253A5)%250A%2520%2520%2520%2520at%2520http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4098%253A40%250A%2520%2520%2520%2520at%2520forEach%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A323%253A20)%250A%2520%2520%2520%2520at%2520loadModules%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4081%253A5)%250A%2520%2520%2520%2520at%2520createInjector%2520(http%253A%252F%252Flocalhost%252Fbower_components%252Fangular%252Fangular.js%253A4007%253A11)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A63%3A12%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4120%3A15%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4098%3A40%0A%20%20%20%20at%20forEach%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A323%3A20)%0A%20%20%20%20at%20loadModules%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4081%3A5)%0A%20%20%20%20at%20createInjector%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A4007%3A11)%0A%20%20%20%20at%20doBootstrap%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A1445%3A20)%0A%20%20%20%20at%20bootstrap%20(http%3A%2F%2Flocalhost%2Fbower_components%2Fangular%2Fangular.js%3A1466%3A12)
    at http://localhost/bower_components/angular/angular.js:63:12
    at http://localhost/bower_components/angular/angular.js:4120:15
    at forEach (http://localhost/bower_components/angular/angular.js:323:20)
    at loadModules (http://localhost/bower_components/angular/angular.js:4081:5)
    at createInjector (http://localhost/bower_components/angular/angular.js:4007:11)
    at doBootstrap (http://localhost/bower_components/angular/angular.js:1445:20)
    at bootstrap (http://localhost/bower_components/angular/angular.js:1466:12)
    at angularInit (http://localhost/bower_components/angular/angular.js:1360:5)
    at HTMLDocument.<anonymous> (http://localhost/bower_components/angular/angular.js:26125:5)
    at mightThrow (http://localhost/bower_components/jquery/dist/jquery.js:3570:29)
```

In `http://localhost/scripts/app.js`
```javascript
68: // spinner on http request
69: angular.module('lelylan.dashboards.device').config(function ($httpProvider) {
70:  $httpProvider.responseInterceptors.push('myHttpInterceptor');
71:  var spinnerFunction = function spinnerFunction(data, headersGetter) {
72:    $("#spinner").show();
73:    return data;
74:   };
75:
76:  $httpProvider.defaults.transformRequest.push(spinnerFunction);
77: });
```

#### Error detail and solution
> The $httpProvider.responseInterceptors is no longer support in 1.3, you have to use $httpProvider.interceptors instead.
